### ISSUE TITLE
Better build instructions

### ISSUE THREAD

**Issue by lpil** [Gankro/too-many-lists#12]
Currently the instructions offered are:

> Building requires an instance of rustbook be set up on your machine. The only way to do this correctly is to build Rust from scratch with ./configure --enable-rpath and steal their copy of rustbook.

This isn't very helpful. [Where do I find this project?](https://www.google.co.uk/search?q=%22rust+from+scratch%22+rustbook&oq=%22rust+from+scratch%22+rustbook&aqs=chrome..69i57.4415j0j7&sourceid=chrome&es_sm=91&ie=UTF-8)

Can we not include the compiler in the repo? Or at least link to it?

**Comment by Gankro** [comment]
Yes, I should link to it -- although honestly I didn't expect anyone to try :sweat_smile:

**Comment by lpil** [comment]
I don't have internet at home, and I spent lots of time on public transport, so I wanted to have a local version to read. :)

**Comment by Gankro** [comment]
I've updated the docs with all I really know about the process. 

Hope that helps!

**Comment by lpil** [comment]
Thanks!
