### ISSUE TITLE
Basic Data Layout unclear on enum vs struct heap allocation issue

### ISSUE THREAD

**Issue by jfager** [Gankro/too-many-lists#7]
My understanding of the respective layouts for the enum vs. struct approaches described in the 'Basic Data Layout' chapter, are, for a two-element list:

`Elem(i32, Box<Elem(i32, Box<Empty>)>)`, two heap allocations.
vs.
`More(Box<{i32, More(Box<{i32, Empty}>)}>)`, also two heap allocations. 

Why is this incorrect?  Or if it is correct, why are the allocations required for the struct case better than those required for the enum case?

**Comment by Gankro** [comment]
Memory consumed:

* first one: (T, ptr) ->  (T, ptr) -> (T, ptr)
* second one: (ptr) -> (T, ptr) -> (T, ptr)

We save on not storing the space for an extra element (which can have unbounded size). We do heap allocate the same amount of memory, but now the list struct itself is doesn't store a T at all. I could probably be clearer about this; it took me a while when reading this issue to recall.

Ultimately though having all elements in uniform storage. Just is *nice*. Particularly when you get to doubly-linked-lists. Having one of the "nodes" be inline sounds like a recipe for disaster with the back-links.

**Comment by Gankro** [comment]
I've significantly expanded the section to hopefully clarify this. http://cglab.ca/~abeinges/blah/too-many-lists/book/first-layout.html

**Comment by jfager** [comment]
This looks great, thanks!
